;  ╔═╗╦ ╦╔═╗╔╦╗╔═╗╔╦╗  ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
;  ╚═╗╚╦╝╚═╗ ║ ║╣ ║║║  ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
;  ╚═╝ ╩ ╚═╝ ╩ ╚═╝╩ ╩   ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝
; The variables for the polybar modules are taken from this file.

;; Edit according to your system
;; Run `ls -1 /sys/class/power_supply/` to list batteries and adapters.
;; Run `ls -1 /sys/class/backlight/` to list available backlight devices.
;;   Common ARM values: backlight, rpi_backlight (Raspberry Pi), pwm-backlight, 10-0045
;; Run `ip link | awk '/state UP/ {print $2}' | tr -d :` to get active network interface.
;;   Common ARM values: eth0, end0 (Pinebook Pro), wlan0 (wireless)

[system]
sys_adapter = AC
sys_battery = BAT0
sys_graphics_card = backlight
sys_network_interface = eth0
;;sys_network_interface2 =
